["U+0020"]
is_abs=false
["U+0021"]
is_abs=false
["U+0022"]
is_abs=false
["U+0023"]
is_abs=false
["U+0024"]
is_abs=false
["U+0025"]
is_abs=false
["U+0026"]
is_abs=false
["U+0027"]
is_abs=false
["U+0028"]
is_abs=false
["U+0029"]
is_abs=false
["U+002A"]
is_abs=false
["U+002B"]
is_abs=false
["U+002C"]
is_abs=false
["U+002D"]
is_abs=false
["U+002E"]
is_abs=false
["U+002F"]
is_abs=false
["U+0030"]
is_abs=false
["U+0031"]
is_abs=false
["U+0032"]
is_abs=false
["U+0033"]
is_abs=false
["U+0034"]
is_abs=false
["U+0035"]
is_abs=false
["U+0036"]
is_abs=false
["U+0037"]
is_abs=false
["U+0038"]
is_abs=false
["U+0039"]
is_abs=false
["U+003A"]
is_abs=false
["U+003B"]
is_abs=false
["U+003C"]
is_abs=false
["U+003D"]
is_abs=false
["U+003E"]
is_abs=false
["U+003F"]
is_abs=false
["U+0040"]
is_abs=false
["U+0041"]
is_abs=false
["U+0042"]
is_abs=false
["U+0043"]
is_abs=false
["U+0044"]
is_abs=false
["U+0045"]
is_abs=false
["U+0046"]
is_abs=false
["U+0047"]
is_abs=false
["U+0048"]
is_abs=false
["U+0049"]
is_abs=false
["U+004A"]
is_abs=false
["U+004B"]
is_abs=false
["U+004C"]
is_abs=false
["U+004D"]
is_abs=false
["U+004E"]
is_abs=false
["U+004F"]
is_abs=false
["U+0050"]
is_abs=false
["U+0051"]
is_abs=false
["U+0052"]
is_abs=false
["U+0053"]
is_abs=false
["U+0054"]
is_abs=false
["U+0055"]
is_abs=false
["U+0056"]
is_abs=false
["U+0057"]
is_abs=false
["U+0058"]
is_abs=false
["U+0059"]
is_abs=false
["U+005A"]
is_abs=false
["U+005B"]
is_abs=false
["U+005C"]
is_abs=false
["U+005D"]
is_abs=false
["U+005E"]
is_abs=false
["U+005F"]
is_abs=false
["U+0060"]
is_abs=false
["U+0061"]
is_abs=false
["U+0062"]
is_abs=false
["U+0063"]
is_abs=false
["U+0064"]
is_abs=false
["U+0065"]
is_abs=false
["U+0066"]
is_abs=false
["U+0067"]
is_abs=false
["U+0068"]
is_abs=false
["U+0069"]
is_abs=false
["U+006A"]
is_abs=false
["U+006B"]
is_abs=false
["U+006C"]
is_abs=false
["U+006D"]
is_abs=false
["U+006E"]
is_abs=false
["U+006F"]
is_abs=false
["U+0070"]
is_abs=false
["U+0071"]
is_abs=false
["U+0072"]
is_abs=false
["U+0073"]
is_abs=false
["U+0074"]
is_abs=false
["U+0075"]
is_abs=false
["U+0076"]
is_abs=false
["U+0077"]
is_abs=false
["U+0078"]
is_abs=false
["U+0079"]
is_abs=false
["U+007A"]
is_abs=false
["U+007B"]
is_abs=false
["U+007C"]
is_abs=false
["U+007D"]
is_abs=false
["U+007E"]
is_abs=false
["U+00A0"]
is_abs=false
["U+00A1"]
is_abs=false
["U+00A2"]
is_abs=false
["U+00A3"]
is_abs=false
["U+00A4"]
is_abs=false
["U+00A5"]
is_abs=false
["U+00A6"]
is_abs=false
["U+00A7"]
is_abs=false
["U+00A8"]
is_abs=false
["U+00A9"]
is_abs=false
["U+00AA"]
is_abs=false
["U+00AB"]
is_abs=false
["U+00AC"]
is_abs=false
["U+00AD"]
is_abs=false
["U+00AE"]
is_abs=false
["U+00AF"]
is_abs=false
["U+00B0"]
is_abs=false
["U+00B1"]
is_abs=false
["U+00B2"]
is_abs=false
["U+00B3"]
is_abs=false
["U+00B4"]
is_abs=false
["U+00B5"]
is_abs=false
["U+00B6"]
is_abs=false
["U+00B7"]
is_abs=false
["U+00B8"]
is_abs=false
["U+00B9"]
is_abs=false
["U+00BA"]
is_abs=false
["U+00BB"]
is_abs=false
["U+00BC"]
is_abs=false
["U+00BD"]
is_abs=false
["U+00BE"]
is_abs=false
["U+00BF"]
is_abs=false
["U+00C0"]
is_abs=false
["U+00C1"]
is_abs=false
["U+00C2"]
is_abs=false
["U+00C3"]
is_abs=false
["U+00C4"]
is_abs=false
["U+00C5"]
is_abs=false
["U+00C6"]
is_abs=false
["U+00C7"]
is_abs=false
["U+00C8"]
is_abs=false
["U+00C9"]
is_abs=false
["U+00CA"]
is_abs=false
["U+00CB"]
is_abs=false
["U+00CC"]
is_abs=false
["U+00CD"]
is_abs=false
["U+00CE"]
is_abs=false
["U+00CF"]
is_abs=false
["U+00D0"]
is_abs=false
["U+00D1"]
is_abs=false
["U+00D2"]
is_abs=false
["U+00D3"]
is_abs=false
["U+00D4"]
is_abs=false
["U+00D5"]
is_abs=false
["U+00D6"]
is_abs=false
["U+00D7"]
is_abs=false
["U+00D8"]
is_abs=false
["U+00D9"]
is_abs=false
["U+00DA"]
is_abs=false
["U+00DB"]
is_abs=false
["U+00DC"]
is_abs=false
["U+00DD"]
is_abs=false
["U+00DE"]
is_abs=false
["U+00DF"]
is_abs=false
["U+00E0"]
is_abs=false
["U+00E1"]
is_abs=false
["U+00E2"]
is_abs=false
["U+00E3"]
is_abs=false
["U+00E4"]
is_abs=false
["U+00E5"]
is_abs=false
["U+00E6"]
is_abs=false
["U+00E7"]
is_abs=false
["U+00E8"]
is_abs=false
["U+00E9"]
is_abs=false
["U+00EA"]
is_abs=false
["U+00EB"]
is_abs=false
["U+00EC"]
is_abs=false
["U+00ED"]
is_abs=false
["U+00EE"]
is_abs=false
["U+00EF"]
is_abs=false
["U+00F0"]
is_abs=false
["U+00F1"]
is_abs=false
["U+00F2"]
is_abs=false
["U+00F3"]
is_abs=false
["U+00F4"]
is_abs=false
["U+00F5"]
is_abs=false
["U+00F6"]
is_abs=false
["U+00F7"]
is_abs=false
["U+00F8"]
is_abs=false
["U+00F9"]
is_abs=false
["U+00FA"]
is_abs=false
["U+00FB"]
is_abs=false
["U+00FC"]
is_abs=false
["U+00FD"]
is_abs=false
["U+00FE"]
is_abs=false
["U+00FF"]
is_abs=false
["U+2013"]
is_abs=false
["U+2014"]
is_abs=false
["U+2015"]
is_abs=false
["U+2017"]
is_abs=false
["U+2018"]
is_abs=false
["U+2019"]
is_abs=false
["U+201A"]
is_abs=false
["U+201B"]
is_abs=false
["U+201C"]
is_abs=false
["U+201D"]
is_abs=false
["U+201E"]
is_abs=false
["U+2020"]
is_abs=false
["U+2021"]
is_abs=false
["U+2022"]
is_abs=false
["U+2026"]
is_abs=false
["U+2032"]
is_abs=false
["U+2033"]
is_abs=false
["U+2039"]
is_abs=false
["U+203A"]
is_abs=false
["U+203C"]
is_abs=false
["U+203E"]
is_abs=false
["U+20AC"]
is_abs=false
["U+2116"]
is_abs=false
["U+2122"]
is_abs=false
["U+2212"]
is_abs=false
["U+FB01"]
is_abs=false
["U+FB02"]
is_abs=false