["U+0020"]
is_abs=false
["U+0021"]
is_abs=false
["U+0022"]
is_abs=false
["U+0023"]
is_abs=false
["U+0024"]
is_abs=false
["U+0025"]
is_abs=false
["U+0026"]
is_abs=false
["U+0027"]
is_abs=false
["U+0028"]
is_abs=false
["U+0029"]
is_abs=false
["U+002A"]
is_abs=false
["U+002B"]
is_abs=false
["U+002C"]
is_abs=false
["U+002D"]
is_abs=false
["U+002E"]
is_abs=false
["U+002F"]
is_abs=false
["U+0030"]
is_abs=false
["U+0031"]
is_abs=false
["U+0032"]
is_abs=false
["U+0033"]
is_abs=false
["U+0034"]
is_abs=false
["U+0035"]
is_abs=false
["U+0036"]
is_abs=false
["U+0037"]
is_abs=false
["U+0038"]
is_abs=false
["U+0039"]
is_abs=false
["U+003A"]
is_abs=false
["U+003B"]
is_abs=false
["U+003C"]
is_abs=false
["U+003D"]
is_abs=false
["U+003E"]
is_abs=false
["U+003F"]
is_abs=false
["U+0040"]
is_abs=false
["U+0041"]
is_abs=false
["U+0042"]
is_abs=false
["U+0043"]
is_abs=false
["U+0044"]
is_abs=false
["U+0045"]
is_abs=false
["U+0046"]
is_abs=false
["U+0047"]
is_abs=false
["U+0048"]
is_abs=false
["U+0049"]
is_abs=false
["U+004A"]
is_abs=false
["U+004B"]
is_abs=false
["U+004C"]
is_abs=false
["U+004D"]
is_abs=false
["U+004E"]
is_abs=false
["U+004F"]
is_abs=false
["U+0050"]
is_abs=false
["U+0051"]
is_abs=false
["U+0052"]
is_abs=false
["U+0053"]
is_abs=false
["U+0054"]
is_abs=false
["U+0055"]
is_abs=false
["U+0056"]
is_abs=false
["U+0057"]
is_abs=false
["U+0058"]
is_abs=false
["U+0059"]
is_abs=false
["U+005A"]
is_abs=false
["U+005B"]
is_abs=false
["U+005C"]
is_abs=false
["U+005D"]
is_abs=false
["U+005E"]
is_abs=false
["U+005F"]
is_abs=false
["U+0060"]
is_abs=false
["U+0061"]
is_abs=false
["U+0062"]
is_abs=false
["U+0063"]
is_abs=false
["U+0064"]
is_abs=false
["U+0065"]
is_abs=false
["U+0066"]
is_abs=false
["U+0067"]
is_abs=false
["U+0068"]
is_abs=false
["U+0069"]
is_abs=false
["U+006A"]
is_abs=false
["U+006B"]
is_abs=false
["U+006C"]
is_abs=false
["U+006D"]
is_abs=false
["U+006E"]
is_abs=false
["U+006F"]
is_abs=false
["U+0070"]
is_abs=false
["U+0071"]
is_abs=false
["U+0072"]
is_abs=false
["U+0073"]
is_abs=false
["U+0074"]
is_abs=false
["U+0075"]
is_abs=false
["U+0076"]
is_abs=false
["U+0077"]
is_abs=false
["U+0078"]
is_abs=false
["U+0079"]
is_abs=false
["U+007A"]
is_abs=false
["U+007B"]
is_abs=false
["U+007C"]
is_abs=false
["U+007D"]
is_abs=false
["U+007E"]
is_abs=false