---
name: docs
on:
  push:
    tags: ["*"]
jobs:
  pub-docs:
    name: Publish MkDocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: nix develop -c uv sync --frozen
      - name: Deploy
        run: |-
          case $GITHUB_REF_NAME in
            doc*-*)
              GITHUB_REF_NAME=$(sed -E 's/^doc.*-/\1/' <<< "$GITHUB_REF_NAME")
              ;;
          esac
          alias=$(case $GITHUB_REF_NAME in
            *-*) echo -n "prerelease" ;;
            *) echo -n "latest" ;;
          esac)
          nix develop -c mike deploy --push --update-aliases "$GITHUB_REF_NAME" "$alias"
