# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: docs
on:
  push:
    tags: ['v*']
  workflow_dispatch:
jobs:
  pub-docs:
    name: Publish MkDocs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
      - name: Deploy
        run: |-
          TAG="$(git describe --abbrev=0 --tags)"
          alias=$(case $TAG in
            *-*) echo -n "prerelease" ;;
            *) echo -n "latest" ;;
          esac)
          mike deploy --push --update-aliases "$TAG" "$alias"
